version: x.x.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Debug
install:
- cmd: git submodule update --init --recursive
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: Ultrapowa Clash Server.sln
  parallel: true
  verbosity: normal
artifacts:
- path: Ultrapowa Clash Server\Debug\
  name: ucs2
